swagger: '2.0'
info:
  title: OMS API
  description: |
    hello
  version: '1.0.0'

schemes:
  - http
  - https

# will be prefixed to all paths
basePath: /api
produces:
  - application/json
consumes:
  - application/json

paths:
  /offer/cheap:
    get:
      summary: Test case
      description: description
      tags:
        - Offers
      consumes:
        - text/plain
      responses:
        200:
          description: bam
        400:
          description: 400
        500:
          description: 500
  /offer/fast:
    get:
      summary: Test case
      description: description
      tags:
        - Offers
      consumes:
        - text/plain
  /offer/{id}:
    get:
      summary: Test case
      description: description
      tags:
        - Offers
      consumes:
        - text/plain
      parameters:
        - name: id
          in: path
          description:
          type: string